FROM node:20-alpine
WORKDIR /app
COPY services/identity-service/package*.json ./
COPY services/identity-service/prisma ./prisma/
RUN npm install --omit=dev
RUN npx prisma generate
COPY services/identity-service/ ./
EXPOSE 5003
CMD ["node", "server.js"]
