FROM node:20-alpine
WORKDIR /app
COPY services/order-service/package*.json ./
COPY services/order-service/prisma ./prisma/
RUN npm install --omit=dev
RUN npx prisma generate
COPY services/order-service/ ./
EXPOSE 5002
CMD ["node", "server.js"]
