FROM node:20-alpine
WORKDIR /app
COPY services/payment-service/package*.json ./
COPY services/payment-service/prisma ./prisma/
RUN npm install --omit=dev
RUN npx prisma generate
COPY services/payment-service/ ./
EXPOSE 5006
CMD ["node", "src/server.js"]
